### ISSUE TITLE
Button does not load if it is hidden behind a wordpress menu on pageload

### ISSUE THREAD

**Issue by funkenstrahlen** [podlove/podlove-subscribe-button#103] opened 2016-05-13 11:39 UTC
I use the default wordpress theme on my podcast page: http://podcast.funkenstrahlen.de/

The subscribe button is added to the sidebar and works nice on a desktop browser.

However on a smartphone the sidebar is initially hidden on pageload and can be enlarged by a hamburger menu. If I do this to show the sidebar on a smartphone the button does not get loaded and displayed.

**Comment by brototyp** [comment] 2016-06-29 17:45
I can confirm this issue. Did you find a workaround @funkenstrahlen ?

**Comment by benzimmer** [comment] 2017-04-03 22:58
Duplicate of #60

**Closed by benzimmer** 2017-04-03 22:58 UTC
