### ISSUE TITLE
URL not correctly transferred to Overcast -> TLS Missing

### ISSUE THREAD

**Issue by luwimi** [podlove/podlove-subscribe-button#165] opened 2018-11-01 11:05 UTC
Subscribing with Overcast on iOS often fails. It seems, that the "s" in https is not transferred to overcast, so that it tries to subscribe via http without tls and fails, when tls is required.
Examples: 
https://systemstart-podcast.de/
https://newz-of-the-world-com/

**Comment by krachtstefan** [comment] 2019-01-20 11:12
I can confirm this issue. It seems like the protocol is not transfered. A url like "https://domain.com/feed" will open in overcast as "domain.com/feed" and prompts with "Could not find a podcast feed at this URL". When manually adding https:// in the input field, it works.

**Comment by thomasdernederlanden** [comment] 2019-03-12 07:44
This is still an issue. I’ve also contacted Marco who’s developing Overcast. Maybe he can fix the issue when the “https://“ is missing.

**Comment by datenreisender** [comment] 2019-03-22 12:38
While Overcast could try both variants, http and https, this is really a thing that should be solved here in the subscribe button. 

I just had the same problem with https://nxtstg.org/: If I view the Podcast URL there it is correctly configured as https://nxtstg.org/feed/mp3, but the subscribe button turns this to `overcast://x-callback-url/add?url=nxtstg.org/feed/mp3` which does not work correctly. `overcast://x-callback-url/add?url=https://nxtstg.org/feed/mp3` on the other hand works as expected.

**Comment by quinncomendant** [comment] 2019-05-11 20:58
This is a fault with the Podlove button. Overcast justifiably requires a scheme in the URL provided to it. 

Works:

- `overcast://x-callback-url/add?url=http://example.com/feed`
- `overcast://x-callback-url/add?url=https://example.com/feed`

Broken:

- `overcast://x-callback-url/add?url=example.com/feed`

Podlove uses the latter.

The solution for me was to update Podlove's `app.js` to include `https://` as part of the URL template:

	{
		title: "Overcast",
		scheme: "overcast://x-callback-url/add?url=http://",
		icon: "ios/overcast.png",
		store: "https://itunes.apple.com/de/app/overcast-podcast-player/id888422857"
	}

**Comment by krachtstefan** [comment] 2019-05-12 04:19
Looks like a good hotfix @quinncomendant!

It seems like podlove is meant to handle the scheme in general. The [prepareURL](https://github.com/podlove/podlove-subscribe-button/blob/1061adee6915951b6a01e0ec2575356eacda7753/src/coffee/clients_panel.coffee#L8
) function has a scheme option that prepends the protocol and it's called in [prepareClients](https://github.com/podlove/podlove-subscribe-button/blob/1061adee6915951b6a01e0ec2575356eacda7753/src/coffee/clients_panel.coffee#L67) after figuring out it if a scheme is available.

I just wonder why it's not available. 🤔Might this be a value that is configurable?

**Comment by benzimmer** [comment] 2019-05-12 09:19
This has been solved a few weeks ago, see this PR for the solution: https://github.com/podlove/podlove-subscribe-button/pull/169

Please note that the code in the PR was merged, but Github did not autoclose it for some reason.

**Closed by benzimmer** 2019-05-12 09:19 UTC
