### ISSUE TITLE
Protocoll missing 

### ISSUE THREAD

**Issue by hinnerkweiler** [podlove/podlove-subscribe-button#161] opened 2018-09-20 07:56 UTC
Using Podlove Subscribe Button to add Podcasts to Overcast it seems like the protocoll part is missed at some point. Overcast complains about a wrong URL, entering https:// manually solves the problem then.

**Comment by quinncomendant** [comment] 2019-05-11 21:00
Duplicate of #165

**Closed** 2019-05-12 09:25 UTC
